export const GETTING_QUESTIONS_BEGINS = 'GETTING_QUESTIONS_BEGINS';
export const GETTING_QUESTIONS_SUCCESS = 'GETTING_QUESTIONS_SUCCESS';
export const GETTING_QUESTIONS_FAILURE = 'GETTING_QUESTIONS_FAILURE';
